### PR TITLE
Stop using CMSDialog, fix click-twice bug

### LINKED ISSUE #99: The "Submit" button in the incomplete data modal only works if you click it twice
The first click seems to shift the focus state from the modal to the button, and the second click actually works

Screen Shot 2020-11-17 at 2 12 25 PM

### PR DESCRIPTION
**Pull request by dmethvin-gov**
Fixes #99 

Switches to CMSDialog to react-modal which we already use. There's one remaining use of CMSDialog.

### CODE REVIEW

File: frontend/src/app/testQueue/QueueItem.jsx [hunk 1]
```diff
@@ -60,24 +60,33 @@ const UPDATE_AOE = gql`
...
+    isOpen={true}
+    style={{
+      content: {
+        top: "50%",
+        left: "50%",
+        width: "40%",
+        marginRight: "-50%",
+        transform: "translate(-50%, -50%)",
+      },
+    }}
```
Comment (sharmaneil) [inline frontend/src/app/testQueue/QueueItem.jsx:73]: would be nice if we eventually the styling out of the component, but no biggie for now

**Review by sharmaneil — APPROVED** [review]
Couldn't run it because my backend causes the app to fail, and i don't want to bang my head debugging it right now. But the code looks good! One more modal to ❌  and then dates!

Thanks dave!
