### PR TITLE
Show a toast notification when patient info is saved

### LINKED ISSUE #140: Something should happen when a user clicks save
On the settings page when a user makes an update to a setting and clicks "Save" they don't get any feedback to let them know that the save happened. We should do something so they know the settings were saved.
(Editing a person is broken right now so I can't see it, but I think it has the same issue.)

Also, the save button looks like it needs some styling.

### PR DESCRIPTION
**Pull request by dmethvin-gov**
Fixes #140 

Screen Shot 2020-11-24 at 10 06 09 AM

### CODE REVIEW

File: frontend/src/app/patients/PatientForm.jsx [hunk 1]
```diff
@@ -182,6 +183,14 @@ const PatientForm = (props) => {
...
       );
     }
+    showNotification(
+      toast,
+      <Alert
+        type="success"
+        title="Patient Saved"
+        body="Patient information has been saved."
+      />
+    );
```
Comment (timothybest-usds) [inline frontend/src/app/patients/PatientForm.jsx:193]: I think this will show even when there is an error. `showNotification` should be called on the success promise handlers for `updatePatient` and `addPatient` line 177 an 182 respectively

Comment (dmethvin-gov) [reply frontend/src/app/patients/PatientForm.jsx:193]: Good catch. I'll update the page to use the user-specific term for "patient" and also spew a generic error on failure since right now nothing happens.

**Review by timothybest-usds — APPROVED** [review]
