### PR TITLE
Disentangled organization identifiers, added device LOINC code.

### LINKED ISSUE #172: Identifiers missing or being used for conflicting purposes
Currently, we have an `external_id` field on the Organization data table, tagged as being for authorization purposes. We also have a `cliaNumber` in the API, which is being mapped to the `external_id` but is actually for public health reporting.

This is actually a bug, because CLIA Number is part of a facility, whereas the organization external ID is supposed to be an immutable property of the organization that we can use in authorization claims from our IDP, and it is not OK for these things to be in the same field. (Also, because the API enforces that external_id is immutable, trying to edit the CLIA Number goes _very_ poorly).

Additionally but sort of unrelatedly, we do not currently store the LOINC for each of our device types, which means that the data hub team will have to maintain a lookup table on our behalf, which seems incorrect design.

### PR DESCRIPTION
**Pull request by benwarfield-usds**
Added new mandatory external identifiers for the facility (CLIA Number) and device type (LOINC code), and made code that was trying unsuccessfully to use the organization external ID as CLIA number use the new field instead.

Resolves #172.

### CODE REVIEW

File: backend/src/main/java/gov/cdc/usds/simplereport/api/model/TestEventExport.java [hunk 1]
```diff
@@ -217,8 +217,7 @@ public String getTestingLabName() {
 
 	@JsonProperty("Testing_lab_ID")
 	public String getTestingLabID() {
-		// CLIA number
-		return org.getExternalId();
+		return org.getCliaNumber();
```
Comment (timothybest-usds) [inline backend/src/main/java/gov/cdc/usds/simplereport/api/model/TestEventExport.java:220]: ❤️ :thank_you:
